# Generated by Django 3.1.6 on 2022-03-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20220327_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('scoreBeg', models.IntegerField(default=0)),
                ('scoreImd', models.IntegerField(default=0)),
                ('scoreExp', models.IntegerField(default=0)),
            ],
        ),
    ]
