# Generated by Django 3.1.6 on 2022-04-25 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20220425_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='subTopic',
        ),
    ]
