# Generated by Django 4.0.1 on 2022-04-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_remove_content_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='text_content',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='video_content',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
