# Generated by Django 4.0.1 on 2022-04-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_remove_content_content_content_text_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='topic',
            new_name='subtopic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='scoreBeg',
        ),
        migrations.RemoveField(
            model_name='student',
            name='scoreExp',
        ),
        migrations.RemoveField(
            model_name='student',
            name='scoreImd',
        ),
        migrations.CreateModel(
            name='AssessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30)),
                ('scoreBeg', models.IntegerField(default=0)),
                ('scoreImd', models.IntegerField(default=0)),
                ('scoreExp', models.IntegerField(default=0)),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.student')),
            ],
        ),
    ]
