# Generated by Django 4.0.1 on 2022-04-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_rename_topic_content_subtopic_remove_student_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='curr_topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
