# Generated by Django 4.0.1 on 2022-04-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_remove_content_text_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
