# Generated by Django 4.0.1 on 2022-04-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_student_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='subTopic',
        ),
    ]
