# Generated by Django 4.0.1 on 2022-04-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_practice_quiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Practice_Quiz',
            new_name='PracticeQuiz',
        ),
    ]
